### ISSUE TITLE
BUG calling org-remark-mark open in shell script file

### ISSUE THREAD

**Issue by ouboub** [nobiot/org-remark#68] opened 2023-07-21 14:58 UTC
Hi

in a shell script I mark a line and either call org-remark-mark or org-remark-open but 
rececive an error which I attach.

[bug-remark.txt](https://github.com/nobiot/org-remark/files/12129942/bug-remark.txt)

**Comment by nobiot** [comment] 2023-07-21 15:22
Thank you. I will look. Can I assume you are in the dev/nov.el branch?

**Comment by ouboub** [comment] 2023-07-21 15:26
> Thank you. I will look. Can I assume you are on the dev/nov.el branch?

yes definetly I just checked

**Comment by nobiot** [comment] 2023-07-21 15:43
Trying to reproduce the error but I cannot. I am using “marginalia.org” with other highlights, as your error indicates that’s how you use it.


It is saying Org-remark is trying to narrow a headline before the first headline. What does your maeginalia.org look like before thr first headline?

**Comment by ouboub** [comment] 2023-07-21 15:45
> Trying to reproduce the error but I cannot. I am using “marginalia.org” with other highlights, as your error indicates that’s how you use it.
> 
> It is saying Org-remark is trying to narrow a headline before the first headline. What does your maeginalia.org look like before thr first headline?

there is no marginalina.org file generated in this case, this is the problem

**Comment by nobiot** [comment] 2023-07-21 16:17
> there is no marginalina.org file generated in this case, this is the problem

I see. What is the value of `org-remark-notes-file-name`? (It’s a user option).

Where is the .sh file in your file system? Perhaps it is in a remote server and Org-remark fails to find the directory?

**Comment by ouboub** [comment] 2023-07-21 16:23
> > there is no marginalina.org file generated in this case, this is the problem
> 
> I see. What is the value of `org-remark-notes-file-name`? (It’s a user option).
> 
> Where is the .sh file in your file system? Perhaps it is in a remote server and Org-remark fails to find the directory?

marginalia.org
I think I have to run some more tests and will report later. something is very odd here.

**Comment by nobiot** [comment] 2023-07-21 16:32
> marginalia.org
> I think I have to run some more tests and will report later. something is very odd here

That’s the default value. At the moment, I cannot reproduce the issue when I have a .sh file in my local directory.

I assume this is not a regression introduced by the recent refactoring…

**Comment by ouboub** [comment] 2023-07-21 19:53
>>> "n" == nobiot  ***@***.***> writes:

>> marginalia.org
>> I think I have to run some more tests and will report later. something is very odd here

> That’s the default value. At the moment, I cannot reproduce the issue
> when I have a .sh file in my local directory.

> I assume this is not a regression introduced by the recent refactoring…

Bad news. Here is what I did 


1. Ok I restarted emacs, returned to the old org-remark everything worked.

2. In an empty directory I copied a shell script file.

3. I opened that file, turned org-remark-mode on

4. I called org-remark-mark 

everything worked as expected.

I returned to the nov branch in github, opened that file.
Then 

    a. Turn on org-remark-mode, then

       - org-remark-open worked.

       - org-remark-mark worked as well.


However when I created a new empty directory and repeated the steps 2-4
above, I obtained the error I mentioned. 

So yes there is a problem. And I don't know why. 





-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the NATO membership of the Ukraine.
I support the EU membership of the Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by nobiot** [comment] 2023-07-21 20:50
Thank you for the detail steps. I’ll try to reproduce the issue.

**Comment by nobiot** [comment] 2023-07-22 08:41
> However when I created a new empty directory and repeated the steps 2-4 above, I obtained the error I mentioned.

I tried this with a new, empty directory. I cannot reproduce the problem. I have no error, marginalia.org gets created, and the highlight gets saved to it, as you normally expect.

Just in case we have different source (I might have pushed some commits after you have pulled the branch), I merged the dev/nov.el branch with main. It will be available via [GNU-devel ELPA](https://elpa.gnu.org/devel/org-remark.html) overnight.

How do you normally update your packags? Via `package.el`? Do you normally use Git to do so?

If you normally use `package.el`, my suggestion is:

- Wait until the GNU-devel gets updated with the new Org-remark commit
- Use `packge.el` to update Org-remark in your normal way
- Then test this issue again

Thank you for staying with me on this. It's a strange issue.

**Comment by ouboub** [comment] 2023-07-22 09:10
>> However when I created a new empty directory and repeated the steps 2-4 above, I obtained the error I mentioned.
> I tried this with a new, empty directory. I cannot reproduce the
> problem. I have no error, marginalia.org gets created, and the
> highlight gets saved to it, as you normally expect.

If I have the time later, I might try to debug it.


> Just in case we have different source (I might have pushed some
> commits after you have pulled the branch), I merged the dev/nov.el
> branch with main. It will be available via [GNU-devel
> ELPA](https://elpa.gnu.org/devel/org-remark.html) overnight.

> How do you normally update your packags? Via `package.el`? Do you
> normally use Git to do so?

I  use git versions only for a handful package, so far org-remark has
not been one of them.

So I still run the offical org-remark-1.0.4 pkg from last year.

> If you normally use `package.el`, my suggestion is:

> - Wait until the GNU-devel gets updated with the new Org-remark commit
> - Use `packge.el` to update Org-remark in your normal way
> - Then test this issue again

> Thank you for staying with me on this. It's a strange issue. 

Maybe debugging will help


-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the NATO membership of the Ukraine.
I support the EU membership of the Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by nobiot** [comment] 2023-07-22 17:57
Looking at your error, I think the commit you use is slightly behind the latest. Could you please try the latest main and see if the problem persists please?

The reason why I think this is that the error should not happen i the current code. See [this line](https://github.com/nobiot/org-remark/blob/main/org-remark.el#L961). In your error stack, the function `org-remark-new-headline` is called with the first argument being number 1.

It is passed as the `level` variable in the function. In the line I quoted above, there is `unless (= level 1)`.  `org-narrow-to-subtree()` should never be called when level is 1, but that’s where your error occurs.
 
I added this `unless` conditional later than when I initially requested you to test the branch. 

I think updating the codebaae to the latest main branch should resolve this issue for you.

**Comment by ouboub** [comment] 2023-07-22 18:30
>>> "n" == nobiot  ***@***.***> writes:

> Looking at your error, I think the commit you use is slightly behind
> the latest. Could you please try the latest main and see if the
> problem persists please?

> The reason why I think this is that the error should not happen i the
> current code. See [this
> line](https://github.com/nobiot/org-remark/blob/main/org-remark.el#L961).
> In your error stack, the function `org-remark-new-headline` is called
> with the first argument being number 1.

> It is passed as the `level` variable in the function. In the line I
> quoted above, there is `unless (= level 1)`. `org-narrow-to-subtree()`
> should never be called when level is 1, but that’s where your error
> occurs.
 
> I added this `unless` conditional later than when I initially
> requested you to test the branch.

> I think updating the codebaae to the latest main branch should resolve
> this issue for you.


Indeed: confirmed, I pulled recompiled, restarted emacs and everything
works now. So you can close that bug (I usually prefer to answer my
email, with emacs I don't like the github issue interface and there is
no working emacs bridge anymore)



-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the NATO membership of the Ukraine.
I support the EU membership of the Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by nobiot** [comment] 2023-07-22 19:26
Mo problem! Thank you 🙏

**Closed** 2023-07-22 19:26 UTC
