### ISSUE TITLE
Highlights inactive after "org-remark-note-body" property is suddently introduced...

### ISSUE THREAD

**Issue by oatmealm** [nobiot/org-remark#46] opened 2022-12-26 16:28 UTC
Hi there! Something is happening in some of the files I'm editing, where the property drawer changes and the highlights in the corresponding file are not shown anymore:

For example, this is how all the highlight headlines in marginalia file look now:

Note the property ```:org-remark-note-body``` which is not present typically, and the position of ```:org-remark-beg``` which should be the first one in the list.
 
```
:org-remark-id: 2804fd1f
:org-remark-label: yellow
:CATEGORY: important
:org-remark-link: [[file:ocr/Horwitz2016.org::30]]
:org-remark-beg: 1543
:org-remark-end: 2216
:org-remark-note-body: Throughout most of the sixteenth century, this community attracted a very
impressive array of....
```

My source file, the one I'n annotating, has this prop line:

```
# -*- org-remark-notes-file-name: "../Horwitz2016.org"; lingva-target: "iw"; -*-
```

I never had any problem until today and all the other annotation, i.e. existing org files I've edited still function as expected.

**Comment by nobiot** [comment] 2022-12-27 04:07
Sorry for the confusion. Org-remaek-note-body should never have become a property. The latest branch notes-sync addresses the issue, and hopefully paves the way to stabilize the new feature.

However, it it still WIP. I am reviewing the code, testing it and using it for my productive use.

At this stage, probably rolling back to https://github.com/nobiot/org-remark/commit/618d60393961f83f0e18881d970f070063064f13 is more stable.

**Comment by nobiot** [comment] 2022-12-27 04:15
Okay, so I have rolled back the main to 618d60393961f83f0e18881d970f070063064f13. It should be more stable. All the latest changes are in PR #48.

You can manually remove :org-remark-note-body: from your notes. It should never been a property in notes files (now fixed in PR #48).

**Comment by oatmealm** [comment] 2022-12-27 07:53
Hi there! 10x for looking into it. I'm currently seeing this: multiple drawers. I've noticed it before, so it's not specifically related to the recent update you've made, but it's present, and I'm not sure how to proceed nor why does it happen. Will probably happen in other files I would edit....

I should add that in this file I manually move/nest headlines created in the designated annotation side file, which I set the  manually in the file I'm annotating, like this:

```
# -*- org-remark-notes-file-name: "../Horwitz2016.org"; lingva-target: "iw"; -*-
```

![image](https://user-images.githubusercontent.com/68159077/209631188-af83b140-764e-4372-a596-4932eb445390.png)

**Comment by nobiot** [comment] 2022-12-29 01:26
> I should add that in this file I manually move/nest headlines created in the designated annotation side file

What does the nested headlines structure look like?

Org-remark expects H1 and H2 like this:

‘’’
* File 1
** Highlight 1 in File 1
** Highlight 2 in File 1
[...]
* File 2
** Highlight 1 in File 2
[...]
‘’’

**Comment by oatmealm** [comment] 2022-12-29 13:05
In this case, only two levels... does org-remark support manually rearranging the headings once they've been created? I guess it looks at UUID...?

**Comment by oatmealm** [comment] 2022-12-29 13:07
> Sorry for the confusion. `org-remark-note-body` should never have become a property. The latest branch notes-sync addresses the issue, and hopefully paves the way to stabilize the new feature.
> 
> However, it it still WIP. I am reviewing the code, testing it and using it for my productive use.
> 
> At this stage, probably rolling back to [618d603](https://github.com/nobiot/org-remark/commit/618d60393961f83f0e18881d970f070063064f13) is more stable.

No problem, so far so good AFAIK! 
Thank you.

**Comment by nobiot** [comment] 2022-12-29 22:57
> In this case, only two levels... does org-remark support manually rearranging the headings once they've been created? I guess it looks at UUID

Yes, I can also manually rearrange the sequence of headlines. It’s based on the H1’s source file name and the H2’s abbreviated UUID.

I cannot reproduce the issue of multiple properties. 

Can you reliably reproduce it with `emacs -Q`?

**Comment by oatmealm** [comment] 2022-12-30 10:28
> Can you reliably reproduce it with `emacs -Q`?

I'm not sure when it happens so can't think of how to reproduce. I've been editing and referencing quite a lot the last couple of days, and it never happens again. So far it's been quite stable. I'll keep and eye and report if I have something useful to add.

**Comment by nobiot** [comment] 2022-12-31 00:31
> So far it's been quite stable. I'll keep and eye and report if I have something useful to add.

Thank you.

**Comment by nobiot** [comment] 2023-01-14 15:56
#51 has gone in with a bunch of fixes to round of the previous update wtih `org-remark-note-body` etc. I'm closing this issue for now; please reopen or create a new one if the issue persists.

**Closed by nobiot** 2023-01-14 15:56 UTC
