### ISSUE TITLE
Possible to turn on mode buffer-local?

### ISSUE THREAD

**Issue by akashpal-21** [nobiot/org-remark#74] opened 2023-12-23 23:54 UTC
I only use this package for files explicitly - I add a prop line in the beginning of the file to evaluate the function that enables this mode.
One problem with this is that - if a file in which this has been evaluated has been opened - any subsequent file I do revert C-x x g ; the package tries to open its note file even if the mode is disabled in the file. I think this is a bug

Secondly; this error pops up when i visit a file with org-remark-mode enabled:
``` 
Error during redisplay: (org-remark-highlights-delay-load #<window 3 on  Preview:test.org>) signaled (wrong-type-argument stringp nil)
 ```

 The relevant function which causes the error is
 
 ```
 (defun org-remark-highlights-delay-load (window)
  "Delay load until WINDOW for current buffer is created."
  (when (windowp window)
    (remove-hook 'window-state-change-functions
                 #'org-remark-highlights-delay-load 'local)
    (org-remark-highlights-load)))
 
```

is it normal ?

**Comment by nobiot** [comment] 2023-12-24 17:43
Any reason why you don’t use `org-remark-global-tracking-mode`? If your notes file name (location) is custom, of the global tracking mode does not find an existing notes file, it does not turn on `org-remark` (that should be the design…). Did it not behave like this?

**Comment by nobiot** [comment] 2023-12-24 17:45
I would also like to analyze what exactly happens. Do you mind providing me more detail of your set up and step-by-step procedure so that I cN reproduce the error?

Thank you 🙏

**Comment by nobiot** [comment] 2023-12-28 10:24
@akashpal-21 Please take your time. No need to feel any pressure.

**Comment by nobiot** [comment] 2023-12-30 16:04
Thank you for the detail. #74 should fix the issue where, in your example, remark0 creates a note buffer. 

I could not replicate your second issue with this error:
>    Error during redisplay: (org-remark-highlights-delay-load #<window 3 on  Preview:test.org>) signaled (wrong-type-argument stringp nil)

I am guessing it may be fixed by this patch too. Please let me know.

---

Two additional comments:

#### 1. Use of File Local Variable

You use this syntax: #** _*_ eval: .... ; _*_`, and you call `revert-buffer` to get it to take effect.

When I call command `add-file-local-variable`, Emacs automatically calls the following. When I kill the Emacs, relaunch it, and visit `remark1` file with this at the end of the file, I get the `org-remark` automatically added without `revert-buffer`. Perhaps this is something you would like to look into.

```org
# Local Variables:
# eval: (org-remark-mode 1)
# End:
```

#### 2. Pop-up to Ask for Read-Only Buffer

The read-only file pop-up seems to be cause by the fact the subdirectory `remark1` (`file-name-sans-extension`) does not exist in the filesystem yet. Org-remark does not add a directory for you. Perhaps the custom code can be adjusted as following so that it can automatically add the subdirectory under `resources`. This way, you don't get the pop-up to confirm (tested on my end).

``` emacs-lisp
  (defun custom/org-remark-note-path ()
    (let ((dir (concat (file-name-directory (buffer-file-name))
                       "resources/"
                       (file-name-sans-extension (buffer-name))
                       "/")))
      (unless (file-exists-p dir) (make-directory dir t))
      (concat dir "notes.org")))
  (setq org-remark-notes-file-path #'custom/org-remark-note-path)
  (setq org-remark-source-file-name 'abbreviate-file-name))
```

**Comment by nobiot** [comment] 2023-12-30 16:12
Thank you for raising this issue; it would have been impossible to notice this error in my code...

**Comment by nobiot** [comment] 2024-01-04 18:09
Thanks for the note. Please keep it open for now. I would like to see if I can replicate what you see. I hope to have to some time in one of the weekends soon (hopefully in January).

**Comment by nobiot** [comment] 2024-04-21 13:16
> The bug I encountered is that if I open remark1 then do 'emacs-client --create-frame' and switch the frame, highlights will try to load on the buffer where org-remark-mode is not active. I tracked the problem to line 1657 `(add-hook 'window-state-change-functions #'org-remark-highlights-delay-load 95 'local)`
> 
> inside the function #'org-remark-highlights-load. I traced the function that is hooked just above and I modified line 1643 to also check whether org-remark-mode is enabled.

Is this the current issue you are reminding me of?

**Comment by nobiot** [comment] 2024-04-21 13:18
And your solution pasted in full in the diff in this comment?
https://github.com/nobiot/org-remark/issues/74#issuecomment-1872656727

**Comment by nobiot** [comment] 2024-04-21 13:19
Not annoyed at all. Just forgotten, apologies. Thanks for keeping me honest.

**Closed as completed** 2024-05-07 17:31 UTC

**Comment by nobiot** [comment] 2024-06-28 07:08
Thank you for letting me know. I was going to come back to this issue. But... no need to come back then?
